<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MovieScreeningsManager.Repositories</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovieScreeningsManager.Storage\MovieScreeningsManager.Storage.csproj" />
    <ProjectReference Include="..\MovieScreeningsManager\MovieScreeningsManager.DBModels.csproj" />
  </ItemGroup>

</Project>
