<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MovieScreeningsManager.Storage</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.51" />
    <PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovieScreeningsManager\MovieScreeningsManager.DBModels.csproj" />
  </ItemGroup>

</Project>
